# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import resource.img_rc
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1411, 874)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 0, 941, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.btn_alter_pwd = QtWidgets.QPushButton(Form)
        self.btn_alter_pwd.setGeometry(QtCore.QRect(1210, 20, 93, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_alter_pwd.setFont(font)
        self.btn_alter_pwd.setObjectName("btn_alter_pwd")
        self.btn_close = QtWidgets.QPushButton(Form)
        self.btn_close.setGeometry(QtCore.QRect(1310, 20, 93, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.lab_log = QtWidgets.QLabel(Form)
        self.lab_log.setGeometry(QtCore.QRect(10, 0, 61, 61))
        self.lab_log.setText("")
        self.lab_log.setObjectName("lab_log")
        self.comb_info_maintain = QtWidgets.QComboBox(Form)
        self.comb_info_maintain.setGeometry(QtCore.QRect(50, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.comb_info_maintain.setFont(font)
        self.comb_info_maintain.setObjectName("comb_info_maintain")
        self.comb_info_maintain.addItem("")
        self.comb_info_maintain.setItemText(0, "")
        self.comb_info_maintain.addItem("")
        self.comb_elective_course = QtWidgets.QComboBox(Form)
        self.comb_elective_course.setGeometry(QtCore.QRect(230, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.comb_elective_course.setFont(font)
        self.comb_elective_course.setObjectName("comb_elective_course")
        self.comb_elective_course.addItem("")
        self.comb_elective_course.setItemText(0, "")
        self.comb_elective_course.addItem("")
        self.comb_elective_course.addItem("")
        self.comb_elective_course.addItem("")
        self.comb_info_select = QtWidgets.QComboBox(Form)
        self.comb_info_select.setGeometry(QtCore.QRect(410, 90, 201, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.comb_info_select.setFont(font)
        self.comb_info_select.setObjectName("comb_info_select")
        self.comb_info_select.addItem("")
        self.comb_info_select.setItemText(0, "")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_info_select.addItem("")
        self.comb_teaching_evaluation = QtWidgets.QComboBox(Form)
        self.comb_teaching_evaluation.setGeometry(QtCore.QRect(620, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.comb_teaching_evaluation.setFont(font)
        self.comb_teaching_evaluation.setObjectName("comb_teaching_evaluation")
        self.comb_teaching_evaluation.addItem("")
        self.comb_teaching_evaluation.setItemText(0, "")
        self.comb_teaching_evaluation.addItem("")
        self.comb_teaching_evaluation.addItem("")
        self.comb_teaching_evaluation.addItem("")
        self.comb_teaching_evaluation.addItem("")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 351, 731))
        self.groupBox.setStyleSheet("QPushButton:hover {\n"
"       cursor: hand; \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.btn_add = QtWidgets.QPushButton(self.groupBox)
        self.btn_add.setGeometry(QtCore.QRect(300, 20, 41, 28))
        self.btn_add.setObjectName("btn_add")
        self.btn_curriculum_select = QtWidgets.QPushButton(self.groupBox)
        self.btn_curriculum_select.setGeometry(QtCore.QRect(30, 80, 60, 60))
        self.btn_curriculum_select.setStyleSheet("\n"
"/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but58.png);\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_curriculum_select.setText("")
        self.btn_curriculum_select.setFlat(True)
        self.btn_curriculum_select.setObjectName("btn_curriculum_select")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 101, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_self_select_course = QtWidgets.QPushButton(self.groupBox)
        self.btn_self_select_course.setGeometry(QtCore.QRect(150, 80, 60, 60))
        self.btn_self_select_course.setStyleSheet("\n"
"/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but60.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_self_select_course.setText("")
        self.btn_self_select_course.setObjectName("btn_self_select_course")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(130, 140, 101, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(130, 270, 101, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.btn_course_Preselection = QtWidgets.QPushButton(self.groupBox)
        self.btn_course_Preselection.setGeometry(QtCore.QRect(150, 210, 60, 60))
        self.btn_course_Preselection.setStyleSheet("\n"
"/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but65.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_course_Preselection.setText("")
        self.btn_course_Preselection.setObjectName("btn_course_Preselection")
        self.btn_grade_select = QtWidgets.QPushButton(self.groupBox)
        self.btn_grade_select.setGeometry(QtCore.QRect(30, 210, 60, 60))
        self.btn_grade_select.setStyleSheet("\n"
"/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but73.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_grade_select.setText("")
        self.btn_grade_select.setObjectName("btn_grade_select")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 101, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(130, 400, 101, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btn_course_select = QtWidgets.QPushButton(self.groupBox)
        self.btn_course_select.setGeometry(QtCore.QRect(150, 340, 60, 60))
        self.btn_course_select.setStyleSheet("/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"\n"
"border-image: url(:/newPrefix/ico_but76.png);\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_course_select.setText("")
        self.btn_course_select.setObjectName("btn_course_select")
        self.btn_self_info = QtWidgets.QPushButton(self.groupBox)
        self.btn_self_info.setGeometry(QtCore.QRect(30, 340, 60, 60))
        self.btn_self_info.setStyleSheet("\n"
"/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but55.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_self_info.setText("")
        self.btn_self_info.setObjectName("btn_self_info")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 400, 91, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(130, 530, 91, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.btn_academic_situation = QtWidgets.QPushButton(self.groupBox)
        self.btn_academic_situation.setGeometry(QtCore.QRect(150, 470, 60, 60))
        self.btn_academic_situation.setStyleSheet("/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but29.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_academic_situation.setText("")
        self.btn_academic_situation.setObjectName("btn_academic_situation")
        self.btn_curriculum_print = QtWidgets.QPushButton(self.groupBox)
        self.btn_curriculum_print.setGeometry(QtCore.QRect(30, 470, 60, 60))
        self.btn_curriculum_print.setStyleSheet("/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but71.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_curriculum_print.setText("")
        self.btn_curriculum_print.setObjectName("btn_curriculum_print")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 530, 91, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.btn_questionnaire = QtWidgets.QPushButton(self.groupBox)
        self.btn_questionnaire.setGeometry(QtCore.QRect(150, 600, 60, 60))
        self.btn_questionnaire.setStyleSheet("/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but29.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_questionnaire.setText("")
        self.btn_questionnaire.setObjectName("btn_questionnaire")
        self.btn_rebuild_course_select = QtWidgets.QPushButton(self.groupBox)
        self.btn_rebuild_course_select.setGeometry(QtCore.QRect(30, 600, 60, 60))
        self.btn_rebuild_course_select.setStyleSheet("/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"\n"
"border-image: url(:/newPrefix/ico_but7.png);\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_rebuild_course_select.setText("")
        self.btn_rebuild_course_select.setObjectName("btn_rebuild_course_select")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 660, 101, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(130, 660, 101, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.btn_idle_classroom = QtWidgets.QPushButton(self.groupBox)
        self.btn_idle_classroom.setGeometry(QtCore.QRect(260, 210, 60, 60))
        self.btn_idle_classroom.setStyleSheet("\n"
"/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but81.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_idle_classroom.setText("")
        self.btn_idle_classroom.setObjectName("btn_idle_classroom")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(240, 660, 101, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.btn_stu_grade_print = QtWidgets.QPushButton(self.groupBox)
        self.btn_stu_grade_print.setGeometry(QtCore.QRect(260, 470, 60, 60))
        self.btn_stu_grade_print.setStyleSheet("/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but8.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_stu_grade_print.setText("")
        self.btn_stu_grade_print.setObjectName("btn_stu_grade_print")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(240, 400, 101, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(240, 140, 101, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.btn_teaching_plan = QtWidgets.QPushButton(self.groupBox)
        self.btn_teaching_plan.setGeometry(QtCore.QRect(260, 340, 60, 60))
        self.btn_teaching_plan.setStyleSheet("/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but25.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_teaching_plan.setText("")
        self.btn_teaching_plan.setObjectName("btn_teaching_plan")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(250, 530, 91, 31))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.btn_stu_evaluate = QtWidgets.QPushButton(self.groupBox)
        self.btn_stu_evaluate.setGeometry(QtCore.QRect(260, 80, 60, 60))
        self.btn_stu_evaluate.setStyleSheet("\n"
"/*border-image: url(:/newPrefix/ico_but58.png);*/\n"
"border-image: url(:/newPrefix/ico_but21.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_stu_evaluate.setText("")
        self.btn_stu_evaluate.setObjectName("btn_stu_evaluate")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(240, 270, 101, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.btn_self_info_maintain = QtWidgets.QPushButton(self.groupBox)
        self.btn_self_info_maintain.setGeometry(QtCore.QRect(260, 600, 60, 60))
        self.btn_self_info_maintain.setStyleSheet("border-image: url(:/newPrefix/ico_but65.png);\n"
"\n"
"cursor:pointer; \n"
"background-color: rgb(25, 35, 45);")
        self.btn_self_info_maintain.setText("")
        self.btn_self_info_maintain.setObjectName("btn_self_info_maintain")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(381, 130, 421, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lab_self_img = QtWidgets.QLabel(self.groupBox_2)
        self.lab_self_img.setGeometry(QtCore.QRect(11, 30, 111, 121))
        self.lab_self_img.setText("")
        self.lab_self_img.setObjectName("lab_self_img")
        self.lab_self_name = QtWidgets.QLabel(self.groupBox_2)
        self.lab_self_name.setGeometry(QtCore.QRect(140, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.lab_self_name.setFont(font)
        self.lab_self_name.setText("")
        self.lab_self_name.setObjectName("lab_self_name")
        self.labe_self_info = QtWidgets.QLabel(self.groupBox_2)
        self.labe_self_info.setGeometry(QtCore.QRect(140, 60, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.labe_self_info.setFont(font)
        self.labe_self_info.setText("")
        self.labe_self_info.setObjectName("labe_self_info")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(811, 130, 591, 161))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 461, 71))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(381, 290, 491, 311))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableView = QtWidgets.QTableView(self.groupBox_4)
        self.tableView.setGeometry(QtCore.QRect(10, 30, 471, 271))
        self.tableView.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.tableView.setObjectName("tableView")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(881, 290, 521, 311))
        self.groupBox_5.setStyleSheet("QTableWidget::item{\n"
"    text-align: center;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 501, 271))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("\n"
"font: 11pt \"Adobe Devanagari\";\n"
"text-align: center;\n"
"border-color: rgb(255, 255, 127);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(26)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 25, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(381, 600, 491, 261))
        self.groupBox_6.setObjectName("groupBox_6")
        self.btn_More_info = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_More_info.setGeometry(QtCore.QRect(390, 20, 93, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_More_info.setFont(font)
        self.btn_More_info.setObjectName("btn_More_info")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(10, 70, 431, 141))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(880, 600, 521, 261))
        self.groupBox_7.setObjectName("groupBox_7")
        self.btn_More_grde = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_More_grde.setGeometry(QtCore.QRect(420, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_More_grde.setFont(font)
        self.btn_More_grde.setObjectName("btn_More_grde")
        self.btn_achievement1 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_achievement1.setGeometry(QtCore.QRect(10, 30, 501, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_achievement1.setFont(font)
        self.btn_achievement1.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"")
        self.btn_achievement1.setText("")
        self.btn_achievement1.setObjectName("btn_achievement1")
        self.btn_achievement2 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_achievement2.setGeometry(QtCore.QRect(10, 70, 501, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_achievement2.setFont(font)
        self.btn_achievement2.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"")
        self.btn_achievement2.setText("")
        self.btn_achievement2.setObjectName("btn_achievement2")
        self.btn_achievement3 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_achievement3.setGeometry(QtCore.QRect(10, 110, 501, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_achievement3.setFont(font)
        self.btn_achievement3.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"")
        self.btn_achievement3.setText("")
        self.btn_achievement3.setObjectName("btn_achievement3")
        self.btn_achievement4 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_achievement4.setGeometry(QtCore.QRect(10, 150, 501, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_achievement4.setFont(font)
        self.btn_achievement4.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"")
        self.btn_achievement4.setText("")
        self.btn_achievement4.setObjectName("btn_achievement4")
        self.btn_achievement5 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_achievement5.setGeometry(QtCore.QRect(10, 190, 501, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.btn_achievement5.setFont(font)
        self.btn_achievement5.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"")
        self.btn_achievement5.setText("")
        self.btn_achievement5.setObjectName("btn_achievement5")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(50, 60, 171, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(230, 60, 171, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(410, 60, 171, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(620, 60, 171, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")

        self.retranslateUi(Form)
        self.btn_close.clicked.connect(Form.Main_window_close)
        self.comb_info_select.activated['QString'].connect(Form.Jump_info_Inquire_page)
        self.comb_teaching_evaluation.activated['QString'].connect(Form.Jump_teaching_evaluation_page)
        self.comb_elective_course.activated['QString'].connect(Form.Jump_elective_course_page)
        self.comb_info_maintain.activated['QString'].connect(Form.Jump_info_maintain_page)
        self.btn_More_grde.clicked.connect(Form.Get_More_Course_Results)
        self.btn_More_info.clicked.connect(Form.Get_More_Msg)
        self.btn_alter_pwd.clicked.connect(Form.Alter_my_pwd)
        self.btn_add.clicked.connect(Form.Add_app)
        self.btn_curriculum_select.clicked.connect(Form.Class_schedule_inquiry)
        self.btn_self_select_course.clicked.connect(Form.Self_selected_course)
        self.btn_stu_evaluate.clicked.connect(Form.Stu_evaluate)
        self.btn_grade_select.clicked.connect(Form.Stu_result_inquiry)
        self.btn_course_Preselection.clicked.connect(Form.Course_pre_selection)
        self.btn_idle_classroom.clicked.connect(Form.Get_Idle_classroom)
        self.btn_self_info.clicked.connect(Form.Get_my_info)
        self.btn_course_select.clicked.connect(Form.Get_elective_course)
        self.btn_teaching_plan.clicked.connect(Form.Look_teaching_plan)
        self.btn_curriculum_print.clicked.connect(Form.Curriculum_print)
        self.btn_academic_situation.clicked.connect(Form.Stu_studies_situation)
        self.btn_stu_grade_print.clicked.connect(Form.Stu_grade_print)
        self.btn_rebuild_course_select.clicked.connect(Form.Get_rebuild_curriculum)
        self.btn_questionnaire.clicked.connect(Form.Get_Questionnaire)
        self.btn_self_info_maintain.clicked.connect(Form.My_info_maintain)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "聊城大学教务系统"))
        self.label.setText(_translate("Form", "聊城大学-教学管理信息服务平台"))
        self.btn_alter_pwd.setText(_translate("Form", "修改密码"))
        self.btn_close.setText(_translate("Form", "退出"))
        self.comb_info_maintain.setItemText(1, _translate("Form", "学生个人信息维护"))
        self.comb_elective_course.setItemText(1, _translate("Form", "学生课表查询"))
        self.comb_elective_course.setItemText(2, _translate("Form", "课程预选"))
        self.comb_elective_course.setItemText(3, _translate("Form", "自主选课"))
        self.comb_info_select.setItemText(1, _translate("Form", "查询个人信息"))
        self.comb_info_select.setItemText(2, _translate("Form", "推荐课表打印"))
        self.comb_info_select.setItemText(3, _translate("Form", "学生课表查询"))
        self.comb_info_select.setItemText(4, _translate("Form", "查询空闲教室"))
        self.comb_info_select.setItemText(5, _translate("Form", "选课名单查询"))
        self.comb_info_select.setItemText(6, _translate("Form", "重修课程查询"))
        self.comb_info_select.setItemText(7, _translate("Form", "学生成绩查询"))
        self.comb_info_select.setItemText(8, _translate("Form", "学生学业情况查询"))
        self.comb_info_select.setItemText(9, _translate("Form", "学生成绩总表打印"))
        self.comb_info_select.setItemText(10, _translate("Form", "教学执行计划查看"))
        self.comb_teaching_evaluation.setItemText(1, _translate("Form", "学生评价"))
        self.comb_teaching_evaluation.setItemText(2, _translate("Form", "过程评价"))
        self.comb_teaching_evaluation.setItemText(3, _translate("Form", "问卷调查"))
        self.comb_teaching_evaluation.setItemText(4, _translate("Form", "教学信息反馈"))
        self.groupBox.setTitle(_translate("Form", "我的应用"))
        self.btn_add.setText(_translate("Form", "添加"))
        self.label_3.setText(_translate("Form", "学生课表查询"))
        self.label_4.setText(_translate("Form", "自主选课"))
        self.label_5.setText(_translate("Form", "课程预选"))
        self.label_6.setText(_translate("Form", "学生成绩查询"))
        self.label_7.setText(_translate("Form", "选课名单查询"))
        self.label_8.setText(_translate("Form", "查询个人信息"))
        self.label_9.setText(_translate("Form", "学生学业情况"))
        self.label_10.setText(_translate("Form", "推荐课表打印"))
        self.label_11.setText(_translate("Form", "重修课程查询"))
        self.label_12.setText(_translate("Form", "问卷调查"))
        self.label_13.setText(_translate("Form", "个人信息维护"))
        self.label_14.setText(_translate("Form", "教学计划查看"))
        self.label_15.setText(_translate("Form", "学生评价"))
        self.label_16.setText(_translate("Form", "学生成绩打印"))
        self.label_17.setText(_translate("Form", "查询空闲教室"))
        self.groupBox_2.setTitle(_translate("Form", "个人信息"))
        self.groupBox_3.setTitle(_translate("Form", "通知"))
        self.label_2.setText(_translate("Form", "暂无通知"))
        self.groupBox_4.setTitle(_translate("Form", "课表"))
        self.groupBox_5.setTitle(_translate("Form", "校历"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "一"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "二"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "三"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "四"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "五"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "六"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "天"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("Form", "21"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "学期"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "2019-2020学年1学期(2019-08-26至2020-01-12)"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "月"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "8月"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "9月"))
        item = self.tableWidget.item(1, 8)
        item.setText(_translate("Form", "10月"))
        item = self.tableWidget.item(1, 13)
        item.setText(_translate("Form", "11月"))
        item = self.tableWidget.item(1, 18)
        item.setText(_translate("Form", "12月"))
        item = self.tableWidget.item(1, 24)
        item.setText(_translate("Form", "1月"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "星期/周"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(2, 7)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(2, 8)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(2, 9)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(2, 10)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.item(2, 11)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(2, 12)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(2, 13)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(2, 14)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.item(2, 15)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.item(2, 16)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.item(2, 17)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.item(2, 18)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.item(2, 19)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.item(2, 20)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.item(2, 21)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.item(2, 22)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.item(2, 23)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.item(2, 24)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.item(2, 25)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "一"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget.item(3, 7)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget.item(3, 9)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(3, 10)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.item(3, 11)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget.item(3, 12)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget.item(3, 14)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(3, 15)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.item(3, 16)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.item(3, 17)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget.item(3, 19)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(3, 20)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(3, 21)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.item(3, 22)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget.item(3, 23)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget.item(3, 25)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "二"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "27"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget.item(4, 8)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(4, 9)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.item(4, 10)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.item(4, 11)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget.item(4, 12)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget.item(4, 14)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(4, 15)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.item(4, 16)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.item(4, 17)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget.item(4, 19)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(4, 20)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(4, 21)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.item(4, 22)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget.item(4, 23)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget.item(4, 25)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "三"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget.item(5, 8)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(5, 9)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(5, 10)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.item(5, 11)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget.item(5, 12)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget.item(5, 14)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(5, 15)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.item(5, 16)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.item(5, 17)
        item.setText(_translate("Form", "27"))
        item = self.tableWidget.item(5, 19)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(5, 20)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.item(5, 21)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.item(5, 22)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget.item(5, 24)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(5, 25)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "四"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget.item(6, 8)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(6, 9)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(6, 10)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.item(6, 11)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget.item(6, 12)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget.item(6, 14)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(6, 15)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.item(6, 16)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget.item(6, 17)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget.item(6, 19)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(6, 20)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.item(6, 21)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.item(6, 22)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget.item(6, 24)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(6, 25)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "五"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.item(7, 5)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("Form", "27"))
        item = self.tableWidget.item(7, 8)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(7, 9)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.item(7, 10)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.item(7, 11)
        item.setText(_translate("Form", "25"))
        item = self.tableWidget.item(7, 13)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(7, 14)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.item(7, 15)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.item(7, 16)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget.item(7, 17)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget.item(7, 19)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(7, 20)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.item(7, 21)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.item(7, 22)
        item.setText(_translate("Form", "27"))
        item = self.tableWidget.item(7, 24)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(7, 25)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "六"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Form", "31"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.item(8, 5)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget.item(8, 8)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(8, 9)
        item.setText(_translate("Form", "12"))
        item = self.tableWidget.item(8, 10)
        item.setText(_translate("Form", "19"))
        item = self.tableWidget.item(8, 11)
        item.setText(_translate("Form", "26"))
        item = self.tableWidget.item(8, 13)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.item(8, 14)
        item.setText(_translate("Form", "9"))
        item = self.tableWidget.item(8, 15)
        item.setText(_translate("Form", "16"))
        item = self.tableWidget.item(8, 16)
        item.setText(_translate("Form", "23"))
        item = self.tableWidget.item(8, 17)
        item.setText(_translate("Form", "30"))
        item = self.tableWidget.item(8, 19)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.item(8, 20)
        item.setText(_translate("Form", "14"))
        item = self.tableWidget.item(8, 21)
        item.setText(_translate("Form", "21"))
        item = self.tableWidget.item(8, 22)
        item.setText(_translate("Form", "28"))
        item = self.tableWidget.item(8, 24)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.item(8, 25)
        item.setText(_translate("Form", "11"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "天"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("Form", "15"))
        item = self.tableWidget.item(9, 5)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget.item(9, 8)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.item(9, 9)
        item.setText(_translate("Form", "13"))
        item = self.tableWidget.item(9, 10)
        item.setText(_translate("Form", "20"))
        item = self.tableWidget.item(9, 11)
        item.setText(_translate("Form", "27"))
        item = self.tableWidget.item(9, 13)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.item(9, 14)
        item.setText(_translate("Form", "10"))
        item = self.tableWidget.item(9, 15)
        item.setText(_translate("Form", "17"))
        item = self.tableWidget.item(9, 16)
        item.setText(_translate("Form", "24"))
        item = self.tableWidget.item(9, 18)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(9, 19)
        item.setText(_translate("Form", "8"))
        item = self.tableWidget.item(9, 20)
        item.setText(_translate("Form", "18"))
        item = self.tableWidget.item(9, 21)
        item.setText(_translate("Form", "22"))
        item = self.tableWidget.item(9, 22)
        item.setText(_translate("Form", "29"))
        item = self.tableWidget.item(9, 24)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.item(9, 25)
        item.setText(_translate("Form", "12"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_6.setTitle(_translate("Form", "消息"))
        self.btn_More_info.setText(_translate("Form", "More..."))
        self.label_22.setText(_translate("Form", "暂无消息"))
        self.groupBox_7.setTitle(_translate("Form", "成绩"))
        self.btn_More_grde.setText(_translate("Form", "More..."))
        self.label_18.setText(_translate("Form", "信息维护"))
        self.label_19.setText(_translate("Form", "选课"))
        self.label_20.setText(_translate("Form", "信息查询"))
        self.label_21.setText(_translate("Form", "教学评价"))
